apiVersion: v2
name: directus
type: application

<<<<<<< HEAD
description: |
  A Helm chart for installing Directus on Kubernetes.
  Directus is a real-time API and App dashboard for managing SQL database content.

home: https://directus.io/

sources:
  - https://github.com/directus-labs/helm-chart/tree/master/charts/directus
  - https://github.com/directus/directus

icon: https://avatars.githubusercontent.com/u/79210894

maintainers:
  - name: mikesindieiev
    email: sindieiev@protonmail.ch
    url: https://github.com/directus-labs/helm-chart

version: 1.0.2
appVersion: "11.1.1"
=======
# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 1.0.2

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "11.1.0"
>>>>>>> 12bdc67 (update chart version, add changelog entry)

dependencies:
- name: mariadb
  version: "~18.0.2"
  repository: "https://charts.bitnami.com/bitnami"
  condition: mariadb.enableInstallation
- name: redis
  version: "~19.6.4"
  repository: "https://charts.bitnami.com/bitnami"
  condition: redis.enabled
